
services:

  # https://github.com/nlmatics/nlm-ingestor
  nlm-ingestor:
    image: jamesmtc/nlm-ingestor:latest
    ports:
      - 5010:5001

  # https://github.com/Unstructured-IO/unstructured-api
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    ports:
      - 8000:8000